# SPDX-FileCopyrightText: 2025 Severen Redwood <sev@severen.dev>
# SPDX-License-Identifier: CC0-1.0

name: Typos
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: typos-${{ github.ref }}
  cancel-in-progress: true

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@v1.29.5
